### ISSUE TITLE
Have screenshots in the repository

### ISSUE THREAD

**Issue by sistason** [kuathadianto/pyracedash#1]
Hi,
I stumbled on this, like probably many people, via google. This project is probably exactly what I want, but I have no way of knowing besides installing and finding out. A screenshot of the main dash window would show instantly that "this is the exactly right this, let's install this!".
Please post a screenshot of your dash in the README ;)

**Comment by kuathadianto** [comment]
Hello @sistason,
Thank you so much for checking my repo! I really didn't expect that anyone would see this (and I'm so happy with that). xD

I just added two short demo videos (just click the images, they are linked to YouTube). I hope that is what you looking for. Actually I really want to complete the documentation from months ago, but I was so busy with my work and don't have much time to finish it. But the code itself is complete (with few bugs but still tolerable) and my friend still use it until now without complaints.

Thanks again and feel free to contact me again! :)

**Comment by sistason** [comment]
Hah, same thing happens with me too, when someone discovers my repo ;)

Yeah, exactly what I wanted, nice job with the videos. I'm searching for this project for my father, so I will show him the frontend-design and then set up a Rpi for that :)
If I find any bugs/more feedback, I will open issues.
